insert into public.products (
  slug,
  name,
  subtitle,
  category,
  collection,
  status,
  featured,
  price,
  compare_at_price,
  description,
  story,
  materials,
  care,
  fit_notes,
  artisan_note,
  image_main,
  image_detail,
  gallery,
  highlights,
  tags,
  palette,
  inventory_count,
  lead_time_days,
  sort_order
)
values
  (
    'nocturne-grid-vest',
    'Nocturne Grid Vest',
    'Open lattice tailoring for late light and sharp layering.',
    'Vest',
    'Evening Structures',
    'active',
    true,
    420.00,
    480.00,
    'A cropped vest with a clean shoulder line and a geometric front lattice that holds shape over silk, jersey, or bare skin.',
    'Built for evening styling, this piece keeps the silhouette narrow while letting the open knot structure create movement around the torso.',
    'Organic cotton cord with reinforced edge binding.',
    'Spot clean only and store flat between wears.',
    'Close through the ribs with enough ease for soft drape underneath.',
    'Knotted in narrow production runs to keep the structure precise.',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1600',
    '["https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1600","https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    array['Editorial structure', 'Layer-friendly shape', 'Small-run atelier finish'],
    array['editorial', 'vest', 'occasion'],
    array['onyx', 'ivory', 'shadow'],
    4,
    10,
    10
  ),
  (
    'lumina-column-dress',
    'Lumina Column Dress',
    'A lean full-length line framed by soft, openwork geometry.',
    'Dress',
    'Signature Weaves',
    'active',
    true,
    560.00,
    620.00,
    'A column dress that balances a body-skimming shape with controlled negative space through the waist and upper back.',
    'This silhouette carries the core VA language: sculptural restraint, texture, and a finish that feels editorial without losing wearability.',
    'Soft organic cotton cord with hidden stabilizing tape in the shoulder and waist.',
    'Spot clean and steam lightly from the reverse side when needed.',
    'Intended to skim rather than compress, with a straight visual line through the body.',
    'Finished by hand with tension checks across every panel.',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1800',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1800',
    '["https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    array['Signature silhouette', 'Open back framing', 'Long vertical line'],
    array['dress', 'signature', 'occasion'],
    array['porcelain', 'sand', 'charcoal'],
    2,
    14,
    20
  ),
  (
    'afterlight-halter-top',
    'Afterlight Halter Top',
    'A compact halter with sharp neckline tension and clean knot spacing.',
    'Top',
    'Evening Structures',
    'active',
    true,
    310.00,
    null,
    'A halter cut to frame the collarbone while keeping the body line minimal, light, and exact.',
    'Designed for warm nights and layered tailoring, the Afterlight keeps the shape controlled without feeling rigid.',
    'Organic cotton cord with soft-touch tie closures.',
    'Spot clean only and reshape while damp if needed.',
    'Fits close through the bust with adjustable neck and back ties.',
    'Each neckline is tension-balanced by hand before finishing.',
    'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1600',
    '["https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    array['Adjustable fit', 'Clean halter neckline', 'Lightweight layering piece'],
    array['halter', 'top', 'night'],
    array['sand', 'black'],
    6,
    7,
    30
  ),
  (
    'solstice-fringe-layer',
    'Solstice Fringe Layer',
    'An airy outer layer with directional fringe and soft movement.',
    'Layer',
    'Daylight Layers',
    'active',
    false,
    445.00,
    null,
    'A longer open layer that skims over dresses and separates, finished with a controlled fringe that moves without overwhelming the silhouette.',
    'The piece was developed as a transitional editorial layer for resort light, private events, and high-summer styling.',
    'Organic cotton cord with soft knotted fringe finish.',
    'Store hanging or folded flat to keep fringe clean and untangled.',
    'Relaxed through the body with easy layering room.',
    'The fringe line is hand-trimmed after the final knot set.',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1600',
    '["https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    array['Resort-ready drape', 'Directional fringe', 'Layering statement'],
    array['layer', 'resort', 'fringe'],
    array['stone', 'oat'],
    3,
    12,
    40
  ),
  (
    'atelier-cascade-set',
    'Atelier Cascade Set',
    'A two-piece top and skirt pairing built around mirrored knot geometry.',
    'Set',
    'Atelier Editions',
    'active',
    false,
    610.00,
    680.00,
    'A matching set with a compact top and elongated skirt, designed to read as one sculptural gesture rather than separate pieces.',
    'The Cascade Set balances structure at the waist with loosened movement through the lower body to keep the look strong but effortless.',
    'Organic cotton cord with hidden waistband support.',
    'Spot clean and store the skirt flat to keep the fall even.',
    'The top fits close, while the skirt sits clean on the waist and relaxes downward.',
    'Panels are tension-matched so the set reads symmetrically front and back.',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1600',
    '["https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    array['Two-piece editorial set', 'Waist-focused shaping', 'Mirror-panel construction'],
    array['set', 'editorial', 'occasion'],
    array['bone', 'espresso'],
    2,
    14,
    50
  ),
  (
    'marais-knot-skirt',
    'Marais Knot Skirt',
    'A straight skirt with an engineered side opening and clean knot columns.',
    'Skirt',
    'Daylight Layers',
    'active',
    false,
    330.00,
    null,
    'A pull-on skirt that sits narrow through the hip and opens subtly through one side panel for a cleaner summer line.',
    'The Marais skirt was built to pair with minimal tops and tailored jackets rather than compete for attention.',
    'Organic cotton cord with soft inner waist facing.',
    'Store flat and avoid hanging for long periods.',
    'Designed to sit at the true waist with a slim but flexible fit.',
    'The side opening is finished by hand so the break point stays sharp.',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Straight line silhouette', 'Subtle side opening', 'Pairs with tailoring'],
    array['skirt', 'resort', 'minimal'],
    array['sand', 'clay'],
    5,
    9,
    60
  ),
  (
    'vesper-shoulder-drape',
    'Vesper Shoulder Drape',
    'A soft over-shoulder piece for evening framing and layered depth.',
    'Accessory',
    'Evening Structures',
    'active',
    false,
    220.00,
    null,
    'A draped accessory that sits across the shoulder and upper arm to add volume, line, and texture to cleaner outfits.',
    'It works as a small styling intervention when the look needs architecture without the weight of a full outer layer.',
    'Fine organic cotton cord with flexible drape.',
    'Store rolled or flat to maintain the shoulder curve.',
    'Adjustable through soft tie points to control where the piece lands.',
    'Each drape is blocked lightly after finishing for consistency.',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Styling layer', 'Shoulder-focused shape', 'Lightweight finish'],
    array['accessory', 'drape', 'styling'],
    array['ivory', 'black'],
    8,
    6,
    70
  ),
  (
    'mirage-frame-top',
    'Mirage Frame Top',
    'A minimal top with sharp borders and an open internal grid.',
    'Top',
    'Resort Grid',
    'active',
    false,
    295.00,
    null,
    'A compact top with clean-edged framing around the bust and a lighter internal weave for contrast and air.',
    'The Mirage top was developed for destination dressing where precision still needs to feel easy and breathable.',
    'Organic cotton cord with reinforced edge lines.',
    'Spot clean, then lay flat to dry fully before storing.',
    'Close fit with light give through the body.',
    'Edges are tightened by hand in the final finishing pass.',
    'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Resort-ready', 'Framed bust line', 'Light internal weave'],
    array['top', 'resort', 'holiday'],
    array['oat', 'sand'],
    7,
    7,
    80
  ),
  (
    'obsidian-column-vest',
    'Obsidian Column Vest',
    'A longerline vest with a strict vertical read and clean open sides.',
    'Vest',
    'Signature Weaves',
    'active',
    false,
    465.00,
    null,
    'A longer vest designed to run close to the body and build a strong vertical line over trousers, shorts, or bare skin.',
    'It gives the archive a sharper tailored edge while keeping the hand-finished knot language intact.',
    'Organic cotton cord with clean edge stabilization.',
    'Spot clean only and steam lightly if the hem needs resetting.',
    'Slim line through the torso with open side movement.',
    'Finished in long panels to keep the column read uninterrupted.',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Long vertical shape', 'Open side construction', 'Tailoring-friendly'],
    array['vest', 'layer', 'tailored'],
    array['black', 'ink'],
    3,
    11,
    90
  ),
  (
    'serein-resort-dress',
    'Serein Resort Dress',
    'A softer day dress with a low back and directional waist framing.',
    'Dress',
    'Resort Grid',
    'active',
    false,
    510.00,
    null,
    'A lighter dress with a calmer drape, designed for destination wardrobes and easier day-to-evening transitions.',
    'The waist framing keeps the silhouette from feeling too loose while the back stays open and understated.',
    'Soft organic cotton cord with flexible waist shaping.',
    'Store flat and steam lightly before wear if needed.',
    'Relaxed fit through the skirt with adjustable tie points through the back.',
    'The lower panels are finished with a softer hand to keep the movement fluid.',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1600',
    '["https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1600"]'::jsonb,
    array['Open low back', 'Flexible waist shaping', 'Day-to-evening ease'],
    array['dress', 'resort', 'day'],
    array['stone', 'shell'],
    4,
    12,
    100
  ),
  (
    'atelier-ribbon-top',
    'Atelier Ribbon Top',
    'An asymmetric top with ribbon-like knot lines around the torso.',
    'Top',
    'Atelier Editions',
    'active',
    false,
    340.00,
    null,
    'An asymmetric top that wraps across the body in a ribbon-like rhythm and leaves deliberate breathing room between each line.',
    'Built for editorials and private appointments, this piece adds shape without relying on bulk.',
    'Organic cotton cord with wrapped edge finish.',
    'Handle gently and store flat to preserve the asymmetry.',
    'Close through the bust with a more fluid lower edge.',
    'Finished asymmetrically by hand so each angle lands cleanly on the body.',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Asymmetric line', 'Editorial styling piece', 'Ribbon-inspired construction'],
    array['top', 'atelier', 'statement'],
    array['bone', 'charcoal'],
    4,
    10,
    110
  ),
  (
    'helios-grid-set',
    'Helios Grid Set',
    'A brighter summer set built around open grid spacing and clean proportions.',
    'Set',
    'Resort Grid',
    'active',
    false,
    575.00,
    null,
    'A two-piece resort set designed to feel lighter and brighter than the evening edit while keeping the same structural precision.',
    'The top and skirt are spaced with wider knot intervals so the full look reads airy, graphic, and sun-ready.',
    'Organic cotton cord with soft structured waistband.',
    'Spot clean and dry flat away from direct heat.',
    'Balanced fit with gentle waist definition and easy movement below.',
    'Each set is checked on form before release to keep the proportions aligned.',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Open summer grid', 'Balanced two-piece look', 'Travel-friendly styling'],
    array['set', 'resort', 'summer'],
    array['sand', 'salt'],
    3,
    12,
    120
  ),
  (
    'night-bloom-drape-dress',
    'Night Bloom Drape Dress',
    'A softer drape-led evening dress with narrow shoulder framing.',
    'Dress',
    'Evening Structures',
    'active',
    false,
    590.00,
    null,
    'A full-length dress that relaxes into a softer body line while keeping the shoulders and upper torso sharply defined.',
    'The contrast between soft drape and strict upper framing gives the piece a more romantic evening attitude.',
    'Organic cotton cord with softened lower-panel finish.',
    'Store flat and avoid compressing the lower drape in storage.',
    'Shoulders fit clean and exact while the lower body falls more freely.',
    'Finished by hand to keep the drape even and the top line controlled.',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1500',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1500',
    '["https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1500"]'::jsonb,
    array['Soft drape lower body', 'Defined shoulders', 'Evening-ready line'],
    array['dress', 'evening', 'soft'],
    array['graphite', 'cream'],
    2,
    14,
    130
  ),
  (
    'private-line-vest',
    'Private Line Vest',
    'A quieter vest with slimmer spacing and a more discreet front line.',
    'Vest',
    'Private Commission',
    'active',
    false,
    430.00,
    null,
    'A reserved version of the VA vest language, built for clients who want shape and handwork without the louder editorial finish.',
    'It holds the same discipline in construction but reads more understated in private wardrobes and event dressing.',
    'Organic cotton cord with compact spacing.',
    'Spot clean and keep folded flat between wears.',
    'Slim fit with minimal extra ease.',
    'The smaller grid requires extra hand-finishing time and tighter tension control.',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1400',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1400',
    '["https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1400"]'::jsonb,
    array['Quiet editorial line', 'Slim spacing', 'Commission-ready finish'],
    array['vest', 'private', 'tailored'],
    array['ivory', 'taupe'],
    2,
    14,
    140
  ),
  (
    'monarch-panel-top',
    'Monarch Panel Top',
    'A panel-led top with pronounced bust framing and slim straps.',
    'Top',
    'Signature Weaves',
    'active',
    false,
    325.00,
    null,
    'A structured top designed around distinct front panels so the openwork feels intentional rather than loose.',
    'The result is a sharper day-to-night piece that works with denim, tailoring, or matching knit underlayers.',
    'Organic cotton cord with reinforced strap finish.',
    'Store flat and avoid pulling from the straps while dressing.',
    'Close fit through the bust and upper ribs with adjustable strap tension.',
    'Panel spacing is hand-measured so the front stays balanced.',
    'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1400',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1400',
    '["https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1400"]'::jsonb,
    array['Panel-led front', 'Adjustable straps', 'Sharper day-to-night top'],
    array['top', 'signature', 'panel'],
    array['black', 'sand'],
    6,
    8,
    150
  ),
  (
    'horizon-column-skirt',
    'Horizon Column Skirt',
    'A longer skirt with uninterrupted vertical knot lines and clean movement.',
    'Skirt',
    'Signature Weaves',
    'active',
    false,
    360.00,
    null,
    'A column skirt designed to extend the body line cleanly while keeping enough movement for real wear.',
    'It is one of the strongest pairing pieces in the archive because it grounds tops, vests, and shoulder layers without visual noise.',
    'Organic cotton cord with internal waist support.',
    'Store flat and steam lightly before wear if needed.',
    'High-waisted slim line with controlled ease through the hem.',
    'Long vertical runs are checked by hand to keep the eye moving cleanly downward.',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1400',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1400',
    '["https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1400"]'::jsonb,
    array['High-waisted line', 'Pairs across the archive', 'Column silhouette'],
    array['skirt', 'column', 'signature'],
    array['stone', 'ink'],
    4,
    9,
    160
  ),
  (
    'atelier-sunframe-layer',
    'Atelier Sunframe Layer',
    'A cropped layer with wide knot spacing and a brighter daytime attitude.',
    'Layer',
    'Daylight Layers',
    'active',
    false,
    390.00,
    null,
    'A cropped layer that adds form around the shoulder and upper torso without closing off the body underneath.',
    'The wide spacing and shorter cut make it an easier daytime entry point into the archive.',
    'Organic cotton cord with light hand-finished edge wrapping.',
    'Store flat and avoid over-folding the shoulder line.',
    'Relaxed upper-body piece intended for layering rather than closure.',
    'The shoulder break is hand-set to keep the cropped line clean.',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1400',
    'https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1400',
    '["https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1400"]'::jsonb,
    array['Daytime entry piece', 'Cropped shoulder line', 'Wide knot spacing'],
    array['layer', 'daylight', 'cropped'],
    array['sand', 'honey'],
    5,
    8,
    170
  ),
  (
    'commission-halo-dress',
    'Commission Halo Dress',
    'A softer bespoke direction reserved for private clients and fittings.',
    'Bespoke',
    'Private Commission',
    'draft',
    false,
    760.00,
    null,
    'A private commission direction with longer lead times, softer shaping, and more room for client adjustments through fittings.',
    'This product is kept in draft so the atelier can adapt the copy, fit, and visual language before presenting it publicly.',
    'Organic cotton cord with custom finish options per commission.',
    'Care varies by finish and is confirmed after the final specification.',
    'Fit is adjusted with the client after consultation and first fitting.',
    'The final knot map changes per commission request.',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1700',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1700',
    '["https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1700"]'::jsonb,
    array['Private commission only', 'Extended atelier lead time', 'Draft listing for internal planning'],
    array['bespoke', 'commission', 'private'],
    array['pearl', 'smoke'],
    1,
    21,
    180
  ),
  (
    'archive-satin-grid-top',
    'Archive Satin Grid Top',
    'A compact top designed to sit under jackets and over silk base layers.',
    'Top',
    'Atelier Archive',
    'active',
    false,
    285.00,
    null,
    'A neat grid top designed for layering with sharper outerwear and softer base textures.',
    'It acts as one of the more commercial archive entries while still holding the brand handwriting.',
    'Organic cotton cord with satin-touch edge finish.',
    'Spot clean and store flat to preserve the panel line.',
    'Close fit for layering under jackets and coats.',
    'The front grid is blocked after finishing to keep the spacing uniform.',
    'https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1400',
    'https://images.pexels.com/photos/1926769/pexels-photo-1926769.jpeg?auto=compress&cs=tinysrgb&w=1400',
    '["https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1400"]'::jsonb,
    array['Layering-focused', 'Commercial archive option', 'Uniform grid finish'],
    array['top', 'archive', 'layering'],
    array['black', 'cream'],
    9,
    7,
    190
  ),
  (
    'veil-structure-layer',
    'Veil Structure Layer',
    'A sheer-feeling outer piece that adds volume without closing the silhouette.',
    'Layer',
    'Atelier Archive',
    'active',
    false,
    470.00,
    null,
    'A light outer piece that sits between accessory and garment, used to frame the body and add movement around sharper looks.',
    'It gives the archive another styling tool for shoots, appointments, and wardrobe building.',
    'Organic cotton cord with airy open spacing.',
    'Store hanging or rolled loosely to avoid hard creases.',
    'Open fit intended to float over the shoulders and torso.',
    'The outer frame is tightened by hand to keep the shape readable in motion.',
    'https://images.pexels.com/photos/1126993/pexels-photo-1126993.jpeg?auto=compress&cs=tinysrgb&w=1400',
    'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=1400',
    '["https://images.pexels.com/photos/291762/pexels-photo-291762.jpeg?auto=compress&cs=tinysrgb&w=1400"]'::jsonb,
    array['Airy outer frame', 'Movement-focused', 'Strong styling tool'],
    array['layer', 'archive', 'editorial'],
    array['fog', 'shell'],
    3,
    11,
    200
  )
on conflict (slug) do update
set name = excluded.name,
    subtitle = excluded.subtitle,
    category = excluded.category,
    collection = excluded.collection,
    status = excluded.status,
    featured = excluded.featured,
    price = excluded.price,
    compare_at_price = excluded.compare_at_price,
    description = excluded.description,
    story = excluded.story,
    materials = excluded.materials,
    care = excluded.care,
    fit_notes = excluded.fit_notes,
    artisan_note = excluded.artisan_note,
    image_main = excluded.image_main,
    image_detail = excluded.image_detail,
    gallery = excluded.gallery,
    highlights = excluded.highlights,
    tags = excluded.tags,
    palette = excluded.palette,
    inventory_count = excluded.inventory_count,
    lead_time_days = excluded.lead_time_days,
    sort_order = excluded.sort_order,
    updated_at = timezone('utc', now());
