export const fallbackCatalogProducts = [
  {
    id: 'home-fallback-1',
    slug: 'nocturne-signal',
    name: 'Nocturne Signal Dress',
    subtitle: 'A lead silhouette shaped for the room that notices everything.',
    category: 'Dress',
    collection: 'Signature Weaves',
    status: 'active',
    featured: true,
    price: 560,
    description: 'A directional dress with the right level of structure, tension, and editorial presence for the home page lead frame.',
    story: 'A longline silhouette staged as the first read of the house: narrow, exact, and strong enough to carry the whole page mood.',
    highlights: ['Lead silhouette', 'Editorial structure', 'Signature pacing'],
    inventory_count: 2,
    lead_time_days: 14,
    sort_order: 10,
  },
  {
    id: 'home-fallback-2',
    slug: 'afterlight-frame-top',
    name: 'Afterlight Frame Top',
    subtitle: 'A sharp top with clean openwork and a precise shoulder line.',
    category: 'Top',
    collection: 'Evening Structures',
    status: 'active',
    featured: true,
    price: 320,
    description: 'Designed for high contrast styling and a crisp night silhouette.',
    story: 'A compact evening piece with the kind of framing that reads quickly in stills and under hard light.',
    highlights: ['Night edit', 'Lightweight structure'],
    inventory_count: 4,
    lead_time_days: 8,
    sort_order: 20,
  },
  {
    id: 'home-fallback-3',
    slug: 'helios-grid-set',
    name: 'Helios Grid Set',
    subtitle: 'An airy two-piece set for bright resort pacing and strong geometry.',
    category: 'Set',
    collection: 'Resort Grid',
    status: 'active',
    featured: false,
    price: 575,
    description: 'A lighter direction with the same strong proportions and graphic spacing.',
    story: 'Built to bring resort light into the collection without softening the underlying structure.',
    highlights: ['Resort direction', 'Two-piece look'],
    inventory_count: 3,
    lead_time_days: 12,
    sort_order: 30,
  },
  {
    id: 'home-fallback-4',
    slug: 'private-line-vest',
    name: 'Private Line Vest',
    subtitle: 'A quieter vest for private-client wardrobes and cleaner styling.',
    category: 'Vest',
    collection: 'Private Commission',
    status: 'active',
    featured: false,
    price: 430,
    description: 'Reserved, tailored, and still unmistakably part of the VA language.',
    story: 'The quieter part of the archive, meant for clients who want discipline over noise.',
    highlights: ['Private client', 'Quiet structure'],
    inventory_count: 1,
    lead_time_days: 14,
    sort_order: 40,
  },
  {
    id: 'home-fallback-5',
    slug: 'ribbon-axis-top',
    name: 'Ribbon Axis Top',
    subtitle: 'An asymmetric frame that wraps the torso in a cleaner diagonal read.',
    category: 'Top',
    collection: 'Atelier Editions',
    status: 'active',
    featured: true,
    price: 355,
    description: 'A more angular editorial top designed for sharper styling and layered looks.',
    story: 'One of the more directional studio pieces, developed for sharper image-making and tighter crop compositions.',
    highlights: ['Asymmetric line', 'Studio direction'],
    inventory_count: 2,
    lead_time_days: 10,
    sort_order: 50,
  },
  {
    id: 'home-fallback-6',
    slug: 'marais-column-skirt',
    name: 'Marais Column Skirt',
    subtitle: 'A narrow skirt with a clean column line and softened side opening.',
    category: 'Skirt',
    collection: 'Daylight Layers',
    status: 'active',
    featured: false,
    price: 340,
    description: 'A narrower day piece for cleaner warm-light styling and lighter movement.',
    story: 'A softer counterweight in the archive, built for layering and quiet daytime dressing rather than pure evening emphasis.',
    highlights: ['Column line', 'Daylight edit'],
    inventory_count: 5,
    lead_time_days: 9,
    sort_order: 60,
  },
];